### ISSUE TITLE
Some items are hidden on smaller screens

### ISSUE THREAD

**Issue by lapadapdap** [bubner/lucasbubner#9]
Due to the way items are presented, they are sometimes partially hidden on smaller screens. This can be fixed by zooming out or going full screen, but that may not be obvious to all users.
This screenshot was taken on a 1366x768 screen using Firefox.

![image](https://github.com/hololb/lucasbubner/assets/99004034/72425cc9-887f-4060-91e4-207bbfe9ab4d)

On other items, it may be touching the navbar or getting very close. The boxes are also inconsistent in size due to them only expanding to fit contents. It may be a good idea to format the items in a way so that the tops of each items are at the same position, but still keeping different heights for each, with the next row starting a bit underneath the tallest box.
This issue is especially annoying on the [links](https://lucasbubner.me/i/links) page, as shown underneath, the Github item is slightly shorter, which may annoy some users.

![image](https://github.com/hololb/lucasbubner/assets/99004034/70d313fd-ff25-4f7a-8434-e591439912b2)

I hope you take some of these ideas into consideration, and please let me know what you think of my suggestions.
Thank you!

**Comment by bubner** [comment]
Will fix soon, thanks for your report!

**Comment by bubner** [comment]
Should be addressed in https://github.com/hololb/lucasbubner/commit/e37bff122819e29de9317ec3daad8dc970d1e80f, might have missed something but will be pushing these changes to prod soon. thank you lachlan paul css for your kind wisdom
